### ISSUE TITLE
Table Schema Rough Draft

### ISSUE THREAD

**Issue by kcamcam** [kcamcam/comp353#1]
I tried to match this up with the most unclear handout in history of handouts, the QA on moodle, and the queries were going to have to ask.    

|  EMPLOYEES | *employee_id*  |  manager | department  | contract  |
|---|---|---|---|---|
|   | PRIMARY KEY  | (boolean)  | (dev,QA,UI...)  | this will hold  |
|   |   |   |   | the FOREIGN KEY  |
|   |   |   |   |  KEY from the  |
|   |   |   |   |  CONTRACTS table  |  

|  CONTRACTS | _*contract_id*_  | first_name  |  last | middle  | phone#  | email_id  | province  | postal_code | ACV | ICV | date| service_type | premium_level |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|   | PRIMARY KEY  |   |   |   | (7digits?)  |  |   |   | Double$  | Double$  |   | (cloud,premise)  | (Silver, Gold, Platiunum, Diamond)  |
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |    

- Note: **Level** is in the CONTRACTS table instead of the EMPLOYEES table, contrary to the handout, it just doesnt seem logical to put that in the employees table.

**Comment by kcamcam** [comment]
Can anyone give some feedback on what they think of this?

**Comment by FredericDesgreniers** [comment]
If companies can have more than one contract, I think they should be in theirs own table with just the key for the company stored in the contracts. 

COMPANIES | company_id | name | first_name | last | middle | email_id 
------------- | ------------ | ------ | ---------- | ---- | ------ | --------
                     | Primary Key |          |                  |        |         |

**Comment by Swallow666** [comment]
Good Job @kcamcam 

Well from my perspective, 
1. Managers cannot be boolean, they are not employees and cannot  have a employee id from the given project description. I think we should split them or just make a "type" as a column and change table name to "company".
2. I think we miss city and company's name in the "contract" table.
3. Should we move email_id and address of company in the "company" table? This one I'm not sure and is this address company's or client's? What u guys think?

Seems contact number problem in ER model already fixed in table though I think it's 10 digits lol

**Comment by Swallow666** [comment]
@FredericDesgreniers I think this CMS is only for 1 company, and the first_middle_last name is for one of the responsible of company (means manager) who is signing the contract.

**Comment by kcamcam** [comment]
@Swallow666 my assumptions for putting managers in the same table as employees are:  
#### From the discussion forum on moodle  
[link to moodle](https://moodle.concordia.ca/moodle/mod/forum/discuss.php?d=417131):  
1.  Can a manager works in multiple department?
    - Manager only manages a contract and it will be wise to assume it if any requirements demands you to think on those lines,otherwise you can put that in assumptions.

2.  Can we put employee and manager in a same table?
    - Yes ,you can.  

#### From the handout:  
[Part1] CMS system should maintain information about:  
1.  Departments - (Development, QA, UI, Design, Business Intelligence, Networking)  
2.  Contracts - (Premium, Gold, Diamond, Silver)  
3.  Managers - (Manager responsible for the contract)  
4.  Employees - (Employee ID)  
5.  Dept.- Employee  
6.  Dept.- Manager  

    - It seems managers are employees, although it is very unclear. Making a separate table for managers and employees creates redundancy for **primary key**, **departments**, and **contract_id**. All 3 attributes already exist in the employees table.

----------  
  
@FredericDesgreniers I believe we're thinking of the same thing, company/contract/client is equivalent. The company we are creating this CSV for (**employees**) offers a service to another company (**clients**) which will have a contract associated to it. If a company(**clients**) would have multiple contracts, we could just create a separate entry for it? Although, I don't see any indication in the handout or the forum of there being more than one contract per client.

----------  

|  EMPLOYEES | *employee_id*  |  manager | department  | contract_id  |
|---|---|---|---|---|
|   | PRIMARY KEY  | (boolean)  | (dev,QA,UI...)  | this will hold  |
|   |   |   |   | the FOREIGN KEY  |
|   |   |   |   |  KEY from the  |
|   |   |   |   |  CONTRACTS table  |  

|  CLIENTS | _*contract_id*_  | company_name |first_name  |  last | middle  | phone#  | email_id | city  | province  | postal_code | ACV | ICV | date| service_type | premium_level |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|   | PRIMARY KEY  |   |   |   |   | (7digits?)  |   |  |   |   | Double$  | Double$  |   | (cloud,premise)  | (Silver, Gold, Platiunum, Diamond)  |
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

Changes: **company_name** and **city** added to the clients table. **CONTRACTS** name table changed to **CLIENTS**

**Comment by FredericDesgreniers** [comment]
@kcamcam 
 In assignment 1, which seems to be related to this warm up project, it states :

>  Question 2
>  Your  query  results  must associate the new contractof a different type butwith the same company i.e., Nike

Which suggests that companies are different than contracts

**Comment by FredericDesgreniers** [comment]
Ok, so this is how I think the schema should look like

EMPLOYEES | employee_id | manager | department | contract
------------ | ------------- | --------- | ------------ | ---------
| | PRIMARY KEY | (boolean) | (dev, QA, UI...) | FOREIGN KEY (contracts) 

CONTRACTS | contract_id |company_id | phone_# | province | city | postal_code | AVC | ICV | date | service_type | premium level
------------- | ----------- | -------------|--------- | -------- | --- | ----------- | ------ | ---  | ----- | ------------ | --------
| | PRIMARY KEY | FOREING KEY (companies) | | | | | double$ | double$ | | (cloud, premise) |  (silver, gold, platinum, diamond)

COMPANIES | company_id | name | repr_first_name | repr_last_name | repr_middle_name | email_id
------------- | ------------| -------|-----------------| -----------------|-------------------|-----------
| | PRIMARY KEY

This way we avoid duplicate info when one company has multiple contracts like the assignment 1 question. We also keep managers and employees the same like @TarikAzz and @kcamcam said.

**Comment by kcamcam** [comment]
☝️Looks good @FredericDesgreniers

**Comment by TarikAzz** [comment]
So we modified the tables a bit, from what @FredericDesgreniers posted and are implementing it now.
