### ISSUE TITLE
Change the file structure

### ISSUE THREAD

**Issue by kcamcam** [kcamcam/comp353#3]
before we submit we should change the file structure to place documents in appropriate `/db`,`/views`, `/routes`  folders. Right now all our files are sitting in the same folder.

We're going to have to change all the file references inside every document, very tedious work. For that reason, lets leave this issue for last, since it doesn't affect performance of our porject.

**Comment by FredericDesgreniers** [comment]
I originally tried to separate it into multiple folders, however php was giving me problems when trying to important things. We can try and give it another try. I think we need to change the include path in the php config to point to the project folder but I'm not 100% sure
