### ISSUE TITLE
Need help for an error

### ISSUE THREAD

**Issue by Swallow666** [kcamcam/comp353#6]
In manager page, now remove function works well (when manager try to remove someone, that one's contractId and manageBy set to 0 for future use).

But, when using add button to add someone to this contract. This error triggered:
** Fatal error: Uncaught TypeError: Argument 1 passed to DatabaseConn::getContractByContractId() must be of the type integer, null given.
I guess it's because add button changing an employee's contractId while contractId is using otherwhere. 
Then I tried to figure it out, but didn't get it right.

Need help!

**Comment by kcamcam** [comment]
what page is this exactly? can you list the steps taken to get this error, starting form the login

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TarikAzz** [comment]
@kcamcam From the login if you login with a manager (id=3) then scroll to the bottom and try to add/assign an employee to the task at the bottom of the page, an exception is thrown.

**Comment by TarikAzz** [comment]
@Swallow666 you fixed the remove button issue?

**Comment by Swallow666** [comment]
@kcamcam the manager page, click add button-->error

**Comment by Swallow666** [comment]
@TarikAzz Remove button works perfect on my local

**Comment by kcamcam** [comment]
PR #8 resolves this issue
