### ISSUE TITLE
Manager page still unable to remove employee from contract

### ISSUE THREAD

**Issue by kcamcam** [kcamcam/comp353#9]
Manager ID 3 still unable to remove employee from contract. MySQL error being thrown is
`removingRegular update error: Cannot add or update a child row: a foreign key constraint fails (comp353.Regular, CONSTRAINT Regular_ibfk_2 FOREIGN KEY (manageBy) REFERENCES Manager (employeeId))`

The SQL is trying to remove employee 4 from the contract:
```
UPDATE Regular SET contractId=0 WHERE employeeId=4;
UPDATE Tasks SET contractId=0 WHERE employeeId=4;
UPDATE Regular SET manageBy=0 WHERE employeeId=4;
```

**Comment by TarikAzz** [comment]
you cant set contractID to 0, it does not exist. We do AUTO INCREMENT.  You'd have to make it null, and in order to do that have to ALTER the table and remove the "NOT NULL" for that attribute.

**Comment by TarikAzz** [comment]
Fixed.
